version: '3.8'
services:
  mysqldb:
    image: mariadb
    container_name: mariadb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=test
      - MARIADB_AUTO_UPGRADE=true
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./dev:/data
  app:
    depends_on:
      - mysqldb
    image: "ghcr.io/vagos/webdevproject:latest"
    build: .
    restart: unless-stopped
    container_name: app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=3306
